### ISSUE TITLE
Server 500 Error bei PUT

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#102]
Vermutung, dass es etwas mit dem Cluster zu tun hat. Neustart hat es behoben

````
09:47:02.251 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format:
09:47:02.251 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
09:47:03.840 [grizzly-http-server-3] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
09:47:03.849 [Incoming-2,DAPNET1.1.3.4,db0sda] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
09:47:03.852 [Incoming-2,DAPNET1.1.3.4,db0sda] INFO  org.dapnet.core.cluster.RpcListener - PutUser User{name='dl8mm'}: OK
09:47:03.924 [grizzly-http-server-3] ERROR org.dapnet.core.cluster.ClusterManager - Response: {db0wa=sender=db0wavalue=OK, received=true, suspecte
d=false, dm0max=sender=dm0maxvalue=NO_QUORUM, received=true, suspected=false, db0sda=sender=db0sdavalue=OK, received=true, suspected=false}
09:47:03.924 [grizzly-http-server-3] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
09:47:03.925 [grizzly-http-server-3] ERROR org.dapnet.core.rest.exceptionHandling.ExceptionHandler - PUT users/dl8mm - Internal Server Error (5000
)
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.dapnet.core.rest.resources.AbstractResource.handleObject(AbstractResource.java:158) ~[dapnet-core-1.1.3.4.jar:1.1.3.4]
        at org.dapnet.core.rest.resources.UserResource.putUser(UserResource.java:90) ~[dapnet-core-1.1.3.4.jar:1.1.3.4]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.1.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.1.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) [grizzly-framework-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) [grizzly-framework-2.3.28.jar:2.3.28]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
````

**Comment by Taronyu** [comment]
Offenbar hat der Knoten dm0max auf den PUT Request mit einem NO_QUORUM
geantwortet. Hast du vielleicht Zugriff auf das Log von dem Knoten? Der
müsste Cluster has no Quorum geloggt haben. Die Logik sagt, es muss mehr
als die Hälfte der registrierten Knoten (also alle mit Status ungleich
SUSPENDED) online sein.

**Comment by Taronyu** [comment]
Hängt das vielleicht mit Ticket #108 zusammen?

**Comment by dh3wr** [comment]
Ja sehr wahrscheinlich. Dann mache ich das hier mal zu.
