### ISSUE TITLE
Core Log von Log Spamming

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#142]
Ich habe Zustand vielleicht nochmal:
````
Nov 17 14:39:09 dapnet java[400]: 14:39:09.599 [INT-2,DAPNET1.1.3.9,db0sda] ERROR org.jgroups.protocols.PDC - JGRP000223: Failed to write temporary file:null
Nov 17 14:39:09 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:09 dapnet java[400]: at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.PDC.writeToTempFile(PDC.java:232) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.PDC.writeNodeToDisk(PDC.java:195) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.PDC.down(PDC.java:89) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.Discovery.down(Discovery.java:440) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.TCPPING.down(TCPPING.java:103) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.AUTH.down(AUTH.java:192) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.MERGE3.down(MERGE3.java:261) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.MERGE3.addInfo(MERGE3.java:333) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.MERGE3.up(MERGE3.java:275) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.AUTH.up(AUTH.java:150) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.Discovery.up(Discovery.java:296) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.stack.Protocol.up(Protocol.java:380) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.TP.passMessageUp(TP.java:1657) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at org.jgroups.protocols.TP$SingleMessageHandler.run(TP.java:1872) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:09 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: 14:39:09.884 [nioEventLoopGroup-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
Nov 17 14:39:09 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:09 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:09 dapnet java[400]: at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:09 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:10 dapnet java[400]: 14:39:10.885 [nioEventLoopGroup-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
Nov 17 14:39:10 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:10 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:10 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_144]
Nov 17 14:39:10 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_144]
Nov 17 14:39:10 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:10 dapnet java[400]: at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:10 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: 14:39:11.354 [INT-1,DAPNET1.1.3.9,db0sda] ERROR org.jgroups.protocols.PDC - JGRP000223: Failed to write temporary file:null
Nov 17 14:39:11 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:11 dapnet java[400]: at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.PDC.writeToTempFile(PDC.java:232) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.PDC.writeNodeToDisk(PDC.java:195) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.PDC.down(PDC.java:89) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.Discovery.down(Discovery.java:440) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.TCPPING.down(TCPPING.java:103) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.Discovery.addDiscoveryResponseToCaches(Discovery.java:550) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.Discovery.up(Discovery.java:322) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.stack.Protocol.up(Protocol.java:380) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.TP.passMessageUp(TP.java:1657) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at org.jgroups.protocols.TP$SingleMessageHandler.run(TP.java:1872) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:11 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: 14:39:11.887 [nioEventLoopGroup-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
Nov 17 14:39:11 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:11 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:11 dapnet java[400]: at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:11 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: 14:39:12.133 [INT-2,DAPNET1.1.3.9,db0sda] ERROR org.jgroups.protocols.PDC - JGRP000223: Failed to write temporary file:null
Nov 17 14:39:12 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:12 dapnet java[400]: at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.PDC.writeToTempFile(PDC.java:232) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.PDC.writeNodeToDisk(PDC.java:195) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.PDC.down(PDC.java:89) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.Discovery.down(Discovery.java:440) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.TCPPING.down(TCPPING.java:103) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.Discovery.addDiscoveryResponseToCaches(Discovery.java:550) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.Discovery.up(Discovery.java:322) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.stack.Protocol.up(Protocol.java:380) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.TP.passMessageUp(TP.java:1657) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.TP$SingleMessageHandler.run(TP.java:1872) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: 14:39:12.639 [INT-1,DAPNET1.1.3.9,db0sda] ERROR org.jgroups.protocols.PDC - JGRP000223: Failed to write temporary file:null
Nov 17 14:39:12 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:12 dapnet java[400]: at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.PDC.writeToTempFile(PDC.java:232) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.PDC.writeNodeToDisk(PDC.java:195) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.PDC.down(PDC.java:89) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.Discovery.down(Discovery.java:440) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.TCPPING.down(TCPPING.java:103) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.Discovery.addDiscoveryResponseToCaches(Discovery.java:550) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.Discovery.up(Discovery.java:322) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.stack.Protocol.up(Protocol.java:380) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.TP.passMessageUp(TP.java:1657) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at org.jgroups.protocols.TP$SingleMessageHandler.run(TP.java:1872) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Nov 17 14:39:12 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: 14:39:12.888 [nioEventLoopGroup-2-1] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
Nov 17 14:39:12 dapnet java[400]: java.io.IOException: Zu viele offene Dateien
Nov 17 14:39:12 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
Nov 17 14:39:12 dapnet java[400]: at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:141) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-all-4.1.15.Final.jar:4.1.15.Final]
Nov 17 14:39:12 dapnet java[400]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

````

**Comment by dh3wr** [comment]
Nach https://stackoverflow.com/questions/4289447/java-too-many-open-files

````
rwth-afu@dapnet:~$ ulimit -n
65536
````

**Comment by Taronyu** [comment]
Siehe #148
