### ISSUE TITLE
 java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#147]
Nur zur Info, vielleicht kann man das sinnvoll abfangen?

````
Dec  3 11:47:08 dapnet java[3823]: 11:47:08.872 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - New View: [on3dhc, db0wa, db0sda, db0ffl, dm0max, db0rta]
Dec  3 11:47:08 dapnet java[3823]: 11:47:08.872 [ViewHandler] WARN  org.dapnet.core.cluster.MembershipListener - Changed status of db0vvs from ONLINE to UNKNOWN
Dec  3 11:47:08 dapnet java[3823]: 11:47:08.873 [ViewHandler] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
Dec  3 11:47:08 dapnet java[3823]: 11:47:08.883 [ViewHandler] INFO  org.dapnet.core.model.State - Successfully wrote state to file
Dec  3 11:47:09 dapnet java[3823]: 11:47:09.674 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters as call.
Dec  3 11:47:09 dapnet java[3823]: 11:47:09.674 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters.
Dec  3 11:47:09 dapnet java[3823]: 11:47:09.674 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - PostNews News{rubricName='dx-vhf uhf', number=3}: OK
Dec  3 11:48:00 dapnet java[3823]: 11:48:00.001 [DefaultQuartzScheduler_Worker-6] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to transmitters.
Dec  3 11:48:51 dapnet java[3823]: 11:48:51.471 [Incoming-2,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus on0sea: OK
Dec  3 11:48:54 dapnet java[3823]: 11:48:54.390 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus on0sea: OK
Dec  3 11:49:00 dapnet java[3823]: 11:49:00.001 [DefaultQuartzScheduler_Worker-4] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to transmitters.
Dec  3 11:49:13 dapnet java[3823]: 11:49:13.644 [Incoming-2,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters as call.
Dec  3 11:49:13 dapnet java[3823]: 11:49:13.644 [Incoming-2,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters.
Dec  3 11:49:13 dapnet java[3823]: 11:49:13.644 [Incoming-2,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - PostNews News{rubricName='dx-vhf uhf', number=4}: OK
Dec  3 11:50:00 dapnet java[3823]: 11:50:00.001 [DefaultQuartzScheduler_Worker-7] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to transmitters.
Dec  3 11:50:00 dapnet java[3823]: 11:50:00.001 [DefaultQuartzScheduler_Worker-8] INFO  org.dapnet.core.transmission.TransmissionManager - Transmitter identifications sent.
Dec  3 11:50:05 dapnet java[3823]: 11:50:05.882 [grizzly-http-server-2] INFO  org.dapnet.core.rest.RestSecurity - No Authorization Data in HttpHeader
Dec  3 11:50:22 dapnet java[3823]: 11:50:22.499 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters as call.
Dec  3 11:50:22 dapnet java[3823]: 11:50:22.499 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters.
Dec  3 11:50:22 dapnet java[3823]: 11:50:22.499 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - PostNews News{rubricName='wetter-nw', number=1}: OK
Dec  3 11:50:30 dapnet java[3823]: 11:50:30.011 [DefaultQuartzScheduler_Worker-1] INFO  org.dapnet.core.model.State - Successfully wrote state to file
Dec  3 11:51:00 dapnet java[3823]: 11:51:00.000 [DefaultQuartzScheduler_Worker-9] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to transmitters.
Dec  3 11:51:24 dapnet java[3823]: 11:51:24.364 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters as call.
Dec  3 11:51:24 dapnet java[3823]: 11:51:24.365 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - News sent to transmitters.
Dec  3 11:51:24 dapnet java[3823]: 11:51:24.365 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - PostNews News{rubricName='dx-kw', number=4}: OK
Dec  3 11:52:00 dapnet java[3823]: 11:52:00.000 [DefaultQuartzScheduler_Worker-3] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to transmitters.
Dec  3 11:52:03 dapnet java[3823]: 11:52:03.794 [TcpServer.Acceptor [7800],null,null] WARN  org.jgroups.protocols.TCP - JGRP000006: failed accepting connection from peer
Dec  3 11:52:03 dapnet java[3823]: java.net.SocketTimeoutException: Read timed out
Dec  3 11:52:03 dapnet java[3823]: at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_151]
Dec  3 11:52:03 dapnet java[3823]: at org.jgroups.blocks.cs.TcpConnection.readPeerAddress(TcpConnection.java:256) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
Dec  3 11:52:03 dapnet java[3823]: at org.jgroups.blocks.cs.TcpConnection.<init>(TcpConnection.java:54) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
Dec  3 11:52:03 dapnet java[3823]: at org.jgroups.blocks.cs.TcpServer$Acceptor.handleAccept(TcpServer.java:119) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
Dec  3 11:52:03 dapnet java[3823]: at org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:104) [jgroups-3.6.13.Final.jar:3.6.13.Final]
Dec  3 11:52:03 dapnet java[3823]: at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Dec  3 11:52:05 dapnet java[3823]: 11:52:05.031 [Incoming-2,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus on0sea: OK
Dec  3 11:52:07 dapnet java[3823]: 11:52:07.898 [Incoming-1,DAPNET1.1.3.9,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus on0sea: OK
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.798 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - New View: [on3dhc, db0wa, db0sda, db0ffl, dm0max, db0rta, db0vvs]
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.798 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - Starting merge process
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.798 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - Node is in majorSubgroup: Nothing to be done
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.798 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - Finished merge process
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.798 [ViewHandler] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of db0vvs from UNKNOWN to ONLINE
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.798 [ViewHandler] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
Dec  3 11:52:55 dapnet java[3823]: 11:52:55.808 [ViewHandler] INFO  org.dapnet.core.model.State - Successfully wrote state to file
````

**Comment by Taronyu** [comment]
Puh, das kommt aus jgroups. Keine Ahnung, ob wir da was machen können.

**Comment by Taronyu** [comment]
Die Exception wird von jgroups geloggt. Keine Ahnung, ob man das abstellen kann. Ad hoc würde ich sagen, das kann man höchstens in eine andere Logdatei mit einer entsprechenden Logconfig umleiten. Aktuell landet das meiste ja im Hauptlog.
