### ISSUE TITLE
Hinzufügen von Sendern zur Gruppe liefert 500 Internal Server Error

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#15]
Ich habe db0eif als Sender hinzugefügt. Alles gut. Beim Hinzufügen zur Sendergruppe kommt Fehler 5000 . Es scheint aber, als ob der Sender trotzdem hinzugefügt wird. Jedenfalls kann man ihn wieder löschen. Hier das Log:

Zunächst Löschen, dann Hinzufügen.

2016-10-03 19:23:02,238 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Request : User: null - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Access-control-request-method=[GET], Origin=[http://db0sda.ampr.org], Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Access-control-request-headers=[authorization], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:02,239 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Response : Header: {Allow=[HEAD,DELETE,GET,OPTIONS,PUT], Content-Length=[0], Content-Type=[text/html], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: null
2016-10-03 19:23:02,285 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST GET Request : User: dh3wr - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Origin=[http://db0sda.ampr.org], Accept=[*/*], Referer=[http://db0sda.ampr.org/dapnet/], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Authorization=[Basic ZGgzd3I6ZGUxcmN3], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:02,295 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST GET Response : Header: {Content-Type=[application/json], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: {  "name": "All",  "description": "All Paging TXes",  "transmitterNames": [    "db0vvs",    "db0koe",    "db0sda_C9000",    "dk2er",    "db0rta",    "db0eif",    "db0kwe"  ],  "ownerNames": [    "dh3wr"  ]}
2016-10-03 19:23:04,694 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Request : User: null - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Access-control-request-method=[PUT], Origin=[http://db0sda.ampr.org], Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Access-control-request-headers=[authorization,content-type], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:04,696 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Response : Header: {Allow=[HEAD,DELETE,GET,OPTIONS,PUT], Content-Length=[0], Content-Type=[text/html], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: null
2016-10-03 19:23:04,743 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST PUT Request : User: dh3wr - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Origin=[http://db0sda.ampr.org], Accept=[application/json, text/javascript, */*; q=0.01], Referer=[http://db0sda.ampr.org/dapnet/], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Authorization=[Basic ZGgzd3I6ZGUxcmN3], Accept-language=[de,en-US;q=0.7,en;q=0.3], Content-type=[application/json], Content-length=[136]} - Entity: {"description":"All Paging TXes","transmitterNames":["db0vvs","db0koe","db0sda_C9000","dk2er","db0rta","db0kwe"],"ownerNames":["dh3wr"]}
2016-10-03 19:23:04,753 INFO org.dapnet.core.cluster.ClusterManager [pool-7-thread-206] Cluster has Quorum
2016-10-03 19:23:04,757 INFO org.dapnet.core.cluster.ClusterManager [Incoming-1,DAPNET0.9.2.3,aprs.db0sda] Cluster has Quorum
2016-10-03 19:23:04,759 INFO org.dapnet.core.cluster.RpcListener [Incoming-1,DAPNET0.9.2.3,aprs.db0sda] PutTransmitterGroup TransmitterGroup{name='All'}: OK
2016-10-03 19:23:04,808 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST PUT Response : Header: {Content-Type=[application/json], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: {  "name": "All",  "description": "All Paging TXes",  "transmitterNames": [    "db0vvs",    "db0koe",    "db0sda_C9000",    "dk2er",    "db0rta",    "db0kwe"  ],  "ownerNames": [    "dh3wr"  ]}
2016-10-03 19:23:05,174 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Request : User: null - Path: /transmitterGroups - Header: {Accept-encoding=[gzip, deflate], Access-control-request-method=[GET], Origin=[http://db0sda.ampr.org], Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Access-control-request-headers=[authorization], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:05,175 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Response : Header: {Allow=[HEAD,GET,OPTIONS], Content-Length=[0], Content-Type=[text/html], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: null
2016-10-03 19:23:05,231 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST GET Request : User: dh3wr - Path: /transmitterGroups - Header: {Accept-encoding=[gzip, deflate], Origin=[http://db0sda.ampr.org], Accept=[*/*], Referer=[http://db0sda.ampr.org/dapnet/], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Authorization=[Basic ZGgzd3I6ZGUxcmN3], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:05,246 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST GET Response : Header: {Content-Type=[application/json], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: [  {    "name": "BAY",    "description": "BAYERN",    "transmitterNames": [      "db0rta"    ],    "ownerNames": [      "dk5rta"    ]  },  {    "name": "NRW",    "description": "NORDRHEIN-WESTFALEN",    "transmitterNames": [      "db0kwe",      "db0vvs",      "db0koe",      "db0sda_C9000",      "dk2er"    ],    "ownerNames": [      "dh3wr"    ]  },  {    "name": "All",    "description": "All Paging TXes",    "transmitterNames": [      "db0vvs",      "db0koe",      "db0sda_C9000",      "dk2er",      "db0rta",      "db0kwe"    ],    "ownerNames": [      "dh3wr"    ]  }]

********  Jetzt HINZUFUEGEN VON DB0EIF **************

2016-10-03 19:23:33,474 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Request : User: null - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Access-control-request-method=[GET], Origin=[http://db0sda.ampr.org], Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Access-control-request-headers=[authorization], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:33,476 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Response : Header: {Allow=[HEAD,DELETE,GET,OPTIONS,PUT], Content-Length=[0], Content-Type=[text/html], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: null
2016-10-03 19:23:33,523 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST GET Request : User: dh3wr - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Origin=[http://db0sda.ampr.org], Accept=[*/*], Referer=[http://db0sda.ampr.org/dapnet/], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Authorization=[Basic ZGgzd3I6ZGUxcmN3], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:33,534 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST GET Response : Header: {Content-Type=[application/json], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: {  "name": "All",  "description": "All Paging TXes",  "transmitterNames": [    "db0vvs",    "db0koe",    "db0sda_C9000",    "dk2er",    "db0rta",    "db0kwe"  ],  "ownerNames": [    "dh3wr"  ]}
2016-10-03 19:23:37,454 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Request : User: null - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Access-control-request-method=[PUT], Origin=[http://db0sda.ampr.org], Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Access-control-request-headers=[authorization,content-type], Accept-language=[de,en-US;q=0.7,en;q=0.3]} - Entity:
2016-10-03 19:23:37,456 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST OPTIONS Response : Header: {Allow=[HEAD,DELETE,GET,OPTIONS,PUT], Content-Length=[0], Content-Type=[text/html], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: null
2016-10-03 19:23:37,503 INFO org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST PUT Request : User: dh3wr - Path: /transmitterGroups/All - Header: {Accept-encoding=[gzip, deflate], Origin=[http://db0sda.ampr.org], Accept=[application/json, text/javascript, */*; q=0.01], Referer=[http://db0sda.ampr.org/dapnet/], Connection=[keep-alive], Host=[aprs.db0sda.ampr.org:8081], User-agent=[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0], Authorization=[Basic ZGgzd3I6ZGUxcmN3], Accept-language=[de,en-US;q=0.7,en;q=0.3], Content-type=[application/json], Content-length=[145]} - Entity: {"description":"All Paging TXes","transmitterNames":["db0vvs","db0koe","db0sda_C9000","dk2er","db0rta","db0eif","db0kwe"],"ownerNames":["dh3wr"]}
2016-10-03 19:23:37,513 INFO org.dapnet.core.cluster.ClusterManager [pool-7-thread-206] Cluster has Quorum
2016-10-03 19:23:37,517 INFO org.dapnet.core.cluster.ClusterManager [Incoming-1,DAPNET0.9.2.3,aprs.db0sda] Cluster has Quorum
2016-10-03 19:23:37,519 INFO org.dapnet.core.cluster.RpcListener [Incoming-1,DAPNET0.9.2.3,aprs.db0sda] PutTransmitterGroup TransmitterGroup{name='All'}: OK
2016-10-03 19:23:37,616 ERROR org.dapnet.core.cluster.ClusterManager [pool-7-thread-206] Response: [sender=db0rta, retval=VALIDATION_ERROR, received=true, suspected=false]
[sender=aprs.db0sda, retval=OK, received=true, suspected=false]
[sender=db0sda, retval=OK, received=true, suspected=false]

2016-10-03 19:23:37,616 FATAL org.dapnet.core.cluster.ClusterManager [pool-7-thread-206] Insecure Cluster State
2016-10-03 19:23:37,617 ERROR org.glassfish.jersey.spi.ExtendedExceptionMapper [pool-7-thread-206] PUT /transmitterGroups/All - Internal Server Error (5000)
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.dapnet.core.rest.resources.AbstractResource.handleObject(AbstractResource.java:142) ~[DAPNET_CORE.jar:?]
        at org.dapnet.core.rest.resources.TransmitterGroupResource.putTransmitterGroup(TransmitterGroupResource.java:59) ~[DAPNET_CORE.jar:?]
        at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:140) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:158) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:101) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:353) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:343) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:237) [jersey-server.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318) [jersey-common.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:211) [jersey-server.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:982) [jersey-server.jar:?]
        at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:164) [jersey-container-jdk-http-2.0.jar:?]
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_101]
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83) [?:1.8.0_101]
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82) [?:1.8.0_101]
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675) [?:1.8.0_101]
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_101]
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
2016-10-03 19:23:37,624 ERROR org.dapnet.core.rest.CustomLoggingFilter [pool-7-thread-206] REST PUT Response : Header: {Content-Type=[application/json], Access-Control-Allow-Origin=[*], Access-Control-Allow-Headers=[Origin, X-Requested-With, Content-Type, Accept, Key, Authorization], Access-Control-Allow-Methods=[GET, POST, PUT, DELETE]} - Entity: {  "code": 5000,  "name": "Internal Server Error",  "message": "A server-side error occurred while executing the request"}

**Comment by DanielSialkowski** [comment]
Dem Log:
2016-10-03 19:23:37,616 ERROR org.dapnet.core.cluster.ClusterManager [pool-7-thread-206] Response: [sender=db0rta, retval=VALIDATION_ERROR, received=true, suspected=false]
[sender=aprs.db0sda, retval=OK, received=true, suspected=false]
[sender=db0sda, retval=OK, received=true, suspected=false]
nach zu schließen hat offensichtlich db0rta einen VALIDATION_ERROR geworfen. Kannst du bitte dort in den Logs nachschauen, was zu dem Fehler geführt hat?

**Comment by dh3wr** [comment]
Nicht wieder aufgetaucht, erstmal geschlossen
