### ISSUE TITLE
Core stops after exception

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#150]
````
03:48:44.896 [TransferQueueBundler,DAPNET1.1.3.10,db0wa] ERROR org.jgroups.protocols.TCP - JGRP000034: db0wa: failure sending message to db0ffl: java.net.SocketTimeoutException: connect timed out
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_111]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_111]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_111]
        at org.jgroups.util.Util.connect(Util.java:411) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.TcpConnection.connect(TcpConnection.java:101) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.TcpConnection.connect(TcpConnection.java:91) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.BaseServer.getConnection(BaseServer.java:271) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.BaseServer.send(BaseServer.java:184) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TCP.send(TCP.java:60) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BasicTCP.sendUnicast(BasicTCP.java:128) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TP.sendToMembers(TP.java:2015) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BasicTCP.sendMulticast(BasicTCP.java:114) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TP.doSend(TP.java:1956) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BaseBundler.sendMessageList(BaseBundler.java:129) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BaseBundler.sendBundledMessages(BaseBundler.java:88) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TransferQueueBundler.run(TransferQueueBundler.java:105) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
03:48:46.946 [Incoming-1,DAPNET1.1.3.10,db0wa] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus db0kwe: OK
03:48:48.901 [TransferQueueBundler,DAPNET1.1.3.10,db0wa] ERROR org.jgroups.protocols.TCP - JGRP000034: db0wa: failure sending message to db0rta: java.net.SocketTimeoutException: connect timed out
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_111]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_111]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_111]
        at org.jgroups.util.Util.connect(Util.java:411) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.TcpConnection.connect(TcpConnection.java:101) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.TcpConnection.connect(TcpConnection.java:91) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.BaseServer.getConnection(BaseServer.java:271) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.blocks.cs.BaseServer.send(BaseServer.java:184) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TCP.send(TCP.java:60) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BasicTCP.sendUnicast(BasicTCP.java:128) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TP.sendToMembers(TP.java:2015) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BasicTCP.sendMulticast(BasicTCP.java:114) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TP.doSend(TP.java:1956) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BaseBundler.sendMessageList(BaseBundler.java:129) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.BaseBundler.sendBundledMessages(BaseBundler.java:88) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.TransferQueueBundler.run(TransferQueueBundler.java:105) [jgroups-3.6.13.Final.jar:3.6.13.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
03:48:53.342 [ViewHandler] INFO  org.dapnet.core.model.State - Successfully wrote state to file
03:48:53.343 [ViewHandler] INFO  org.dapnet.core.DAPNETCore - DAPNETCore stopped
03:48:53.348 [ShutdownHook] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNETCore ...
03:48:53.350 [ShutdownHook] INFO  org.dapnet.core.rest.RestManager - RestApi successfully stopped.
03:48:53.351 [ShutdownHook] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully stopped
03:48:53.351 [ShutdownHook] INFO  org.dapnet.core.transmission.TransmitterServer - Server stopped.
03:48:53.448 [ShutdownHook] INFO  org.dapnet.core.model.State - Successfully wrote state to file
03:48:53.448 [ShutdownHook] INFO  org.dapnet.core.DAPNETCore - DAPNETCore stopped
````

**Comment by Taronyu** [comment]
Joah, connect timeout heißt die Gegenseite antwortet nicht. Netzwerkprobleme oder der andere Knoten ist abgeschmiert.
