### ISSUE TITLE
Stopping Core?

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#30]
Knoten aprs.db0sda:

War heute morgen suspended auf db0sda.ampr.org angezeigt. Logs von gestern

rwth-afu@aprs:/opt/DAPNET_CORE/logs$ zcat DAPNET_CORE-10-30-2016.log.gz

2016-10-30 10:00:15,002 INFO org.dapnet.core.transmission.TransmissionManager [DefaultQuartzScheduler_Worker-4] Rubric sent using 0 Transmitter
2016-10-30 10:00:30,043 INFO org.dapnet.core.model.State [DefaultQuartzScheduler_Worker-5] Successfully wrote state to file
2016-10-30 10:01:03,933 WARN org.dapnet.core.cluster.MembershipListener [VERIFY_SUSPECT.TimerThread,DAPNET0.9.3.0,aprs.db0sda] Node db0rta is suspected
2016-10-30 10:01:04,036 INFO org.dapnet.core.cluster.MembershipListener [Thread-210] New View: [aprs.db0sda|234] (2) [aprs.db0sda, db0sda]
2016-10-30 10:01:04,037 WARN org.dapnet.core.cluster.MembershipListener [Thread-210] Changed status of db0rta from ONLINE to UNKNOWN
2016-10-30 10:01:04,038 INFO org.dapnet.core.cluster.ClusterManager [Thread-210] Cluster has Quorum
2016-10-30 10:01:04,057 INFO org.dapnet.core.model.State [Thread-210] Successfully wrote state to file
2016-10-30 10:01:26,463 INFO org.dapnet.core.cluster.MembershipListener [Thread-211] New View: MergeView::[db0rta|235] (3) [db0rta, aprs.db0sda, db0sda], 2 subgroups: [aprs.db0sda|234] (2) [aprs.db0sda, db0sda], [db0rta|234] (2) [db0rta, db0sda]
2016-10-30 10:01:26,466 INFO org.dapnet.core.cluster.MembershipListener [Thread-211] Starting merge process
2016-10-30 10:01:26,467 INFO org.dapnet.core.cluster.MembershipListener [Thread-211] Node is in majorSubgroup: Nothing to be done
2016-10-30 10:01:26,467 INFO org.dapnet.core.cluster.MembershipListener [Thread-211] Finished merge process
2016-10-30 10:01:26,468 INFO org.dapnet.core.cluster.MembershipListener [Thread-211] Changed status of db0rta from UNKNOWN to ONLINE
2016-10-30 10:01:26,468 INFO org.dapnet.core.cluster.ClusterManager [Thread-211] Cluster has Quorum
2016-10-30 10:01:26,498 INFO org.dapnet.core.model.State [Thread-211] Successfully wrote state to file
2016-10-30 10:01:58,897 INFO org.dapnet.core.transmission.TransmissionManager [Incoming-2,DAPNET0.9.3.0,aprs.db0sda] Call sent to 1 CallSigns, to 1 Pager, using 1 TransmitterGroups and 0 Transmitter
2016-10-30 10:01:58,897 INFO org.dapnet.core.cluster.RpcListener [Incoming-2,DAPNET0.9.3.0,aprs.db0sda] PostCall Call{ownerName='do1kmt'}: OK
2016-10-30 10:03:42,939 WARN org.dapnet.core.cluster.MembershipListener [VERIFY_SUSPECT.TimerThread,DAPNET0.9.3.0,aprs.db0sda] Node db0rta is suspected
2016-10-30 10:03:43,042 INFO org.dapnet.core.cluster.MembershipListener [Thread-212] New View: [aprs.db0sda|236] (2) [aprs.db0sda, db0sda]
2016-10-30 10:03:43,044 WARN org.dapnet.core.cluster.MembershipListener [Thread-212] Changed status of db0rta from ONLINE to UNKNOWN
2016-10-30 10:03:43,045 INFO org.dapnet.core.cluster.ClusterManager [Thread-212] Cluster has Quorum
2016-10-30 10:03:43,075 INFO org.dapnet.core.model.State [Thread-212] Successfully wrote state to file
2016-10-30 10:03:59,569 INFO org.dapnet.core.cluster.MembershipListener [Thread-213] New View: MergeView::[db0sda|237] (3) [db0sda, db0rta, aprs.db0sda], 2 subgroups: [db0rta|236] (2) [db0rta, db0sda], [aprs.db0sda|236] (2) [aprs.db0sda, db0sda]
2016-10-30 10:03:59,574 INFO org.dapnet.core.cluster.MembershipListener [Thread-213] Starting merge process
2016-10-30 10:03:59,595 INFO org.dapnet.core.cluster.ClusterManager [Thread-213] Cluster has Quorum
**2016-10-30 10:03:59,595 FATAL org.dapnet.core.cluster.MembershipListener [Thread-213] Node has quorum although it is the minoritySubgroup (Seems to merge independent clusters). Stopping minority group.**
2016-10-30 10:03:59,595 INFO org.dapnet.core.DAPNETCore [Thread-213] Stopping DAPNET_CORE...
2016-10-30 10:03:59,596 INFO org.dapnet.core.transmission.TransmitterDeviceManager [Thread-213] Successfully disconnected from all Transmitters
2016-10-30 10:03:59,609 WARN org.dapnet.core.cluster.ClusterManager [Incoming-2,DAPNET0.9.3.0,aprs.db0sda] Cluster has no Quroum
2016-10-30 10:03:59,610 INFO org.dapnet.core.cluster.RpcListener [Incoming-2,DAPNET0.9.3.0,aprs.db0sda] UpdateNodeStatus aprs.db0sda to SUSPENDED: OK
2016-10-30 10:04:04,110 INFO org.dapnet.core.model.State [Thread-213] Successfully wrote state to file
2016-10-30 10:04:04,113 INFO org.dapnet.core.rest.RestManager [Thread-213] RestApi successfully stopped
2016-10-30 10:04:04,114 INFO org.dapnet.core.scheduler.SchedulerManager [Thread-213] SchedulerManager successfully stopped
2016-10-30 10:04:04,115 INFO org.dapnet.core.cluster.MembershipListener [Thread-213] Finished merge process
2016-10-30 10:04:04,116 INFO org.dapnet.core.cluster.MembershipListener [Thread-213] Changed status of aprs.db0sda from SUSPENDED to ONLINE
2016-10-30 10:04:04,116 INFO org.dapnet.core.cluster.MembershipListener [Thread-213] Changed status of db0rta from UNKNOWN to ONLINE
2016-10-30 10:04:04,117 INFO org.dapnet.core.cluster.ClusterManager [Thread-213] Cluster has Quorum
2016-10-30 10:04:04,154 INFO org.dapnet.core.model.State [Thread-213] Successfully wrote state to file

- Das heißt, wenn das Cluster zerfällt, und beide Teile mayority haben, dann geht ein Teil komplett offline?

Log von heute:
rwth-afu@aprs:/opt/DAPNET_CORE/logs$ cat DAPNET_CORE.log
2016-10-31 09:58:17,541 INFO org.dapnet.core.DAPNETCore [main] Stopping DAPNET_CORE...
2016-10-31 09:58:17,546 INFO org.dapnet.core.transmission.TransmitterDeviceManager [main] Successfully disconnected from all Transmitters
2016-10-31 09:58:17,547 ERROR org.dapnet.core.cluster.ClusterManager [main] catching
java.lang.IllegalStateException: channel is not connected
        at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.down(MessageDispatcher.java:692) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.RequestCorrelator.sendRequest(RequestCorrelator.java:175) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.GroupRequest.sendRequest(GroupRequest.java:360) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.GroupRequest.sendRequest(GroupRequest.java:103) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.Request.execute(Request.java:83) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.MessageDispatcher.cast(MessageDispatcher.java:367) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.MessageDispatcher.cast(MessageDispatcher.java:373) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.MessageDispatcher.castMessage(MessageDispatcher.java:258) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.RpcDispatcher.callRemoteMethods(RpcDispatcher.java:159) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.jgroups.blocks.RpcDispatcher.callRemoteMethods(RpcDispatcher.java:122) ~[jgroups-3.6.3.Final.jar:3.6.3.Final]
        at org.dapnet.core.cluster.ClusterManager.handleStateOperation(ClusterManager.java:213) [DAPNET_CORE.jar:?]
        at org.dapnet.core.cluster.ClusterManager.updateNodeStatus(ClusterManager.java:228) [DAPNET_CORE.jar:?]
        at org.dapnet.core.cluster.ClusterManager.handleDisconnectedFromAllTransmitters(ClusterManager.java:264) [DAPNET_CORE.jar:?]
        at org.dapnet.core.transmission.TransmitterDeviceManager.disconnectFromAllTransmitters(TransmitterDeviceManager.java:140) [DAPNET_CORE.jar:?]
        at org.dapnet.core.cluster.ClusterManager.stop(ClusterManager.java:149) [DAPNET_CORE.jar:?]
        at org.dapnet.core.DAPNETCore.stop(DAPNETCore.java:75) [DAPNET_CORE.jar:?]
        at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:58) [DAPNET_CORE.jar:?]
        at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:104) [DAPNET_CORE.jar:?]
2016-10-31 09:58:17,582 FATAL org.dapnet.core.cluster.ClusterManager [main] Insecure Cluster State
2016-10-31 09:58:17,608 INFO org.dapnet.core.model.State [main] Successfully wrote state to file
2016-10-31 09:58:17,609 INFO org.dapnet.core.rest.RestManager [main] RestApi successfully stopped
2016-10-31 09:58:17,610 INFO org.dapnet.core.scheduler.SchedulerManager [main] SchedulerManager successfully stopped

- Wie man sieht, ist von 30.10.16 10 Uhr bis heute morgen, als ich "stop" eingab, nichts passiert. Sollten sich die Core nicht unentwegt versuchen wieder zu verbinden? Es scheint, als ob nach dem "Stopping Core" von gestern der Core nichts mehr macht.

**Comment by dh3wr** [comment]
Noch etwas:
RESTAPI wurde gestoppt, aber nie wieder gestartet. Bug oder Feature?


10:09:42.816 [Thread-22] INFO  org.dapnet.core.cluster.MembershipListener - Starting merge process
10:09:42.816 [Thread-22] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
10:09:42.816 [Thread-22] FATAL org.dapnet.core.cluster.MembershipListener - Node has quorum although it is the minoritySubgroup (Seems to merge independent clusters). Stopping minority group.
10:09:42.816 [Thread-22] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNET_CORE...
10:09:42.816 [Thread-22] INFO  org.dapnet.core.rest.RestManager - RestApi successfully stopped
10:09:42.817 [Thread-22] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully stopped
10:09:42.817 [Thread-22] INFO  org.dapnet.core.cluster.MembershipListener - Finished merge process
10:09:42.817 [Thread-22] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of aprs.db0sda from SUSPENDED to ONLINE
10:09:42.817 [Thread-22] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
10:09:42.831 [Thread-22] INFO  org.dapnet.core.model.State - Successfully wrote state to file
10:11:22.510 [Incoming-1,DAPNET0.9.3.0,db0sda] INFO  org.dapnet.core.transmission.TransmissionManager - Call sent to 1 CallSigns, to 1 Pager, using 1 TransmitterGroups and 0 Transmitter
10:11:22.510 [Incoming-1,DAPNET0.9.3.0,db0sda] INFO  org.dapnet.core.cluster.RpcListener - PostCall Call{ownerName='dk5rta'}: OK
10:14:25.658 [Thread-23] INFO  org.dapnet.core.cluster.MembershipListener - New View: [db0rta|1225] (3) [db0rta, raspberry.db0rta, db0sda]
10:14:25.658 [Thread-23] WARN  org.dapnet.core.cluster.MembershipListener - Changed status of aprs.db0sda from ONLINE to UNKNOWN
10:14:25.658 [Thread-23] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
10:14:25.662 [Thread-23] INFO  org.dapnet.core.model.State - Successfully wrote state to file
10:14:25.958 [VERIFY_SUSPECT.TimerThread,DAPNET0.9.3.0,db0sda] WARN  org.dapnet.core.cluster.MembershipListener - Node db0rta is suspected
10:14:55.094 [Thread-24] INFO  org.dapnet.core.cluster.MembershipListener - New View: MergeView::[db0rta|1226] (4) [db0rta, raspberry.db0rta, db0sda, aprs.db0sda], 2 subgroups: [db0rta|1224] (4) [db0rta, raspberry.db0rta, aprs.db0sda, db0sda], [db0rta|1225] (3) [db0rta, raspberry.db0rta, db0sda]
10:14:55.094 [Thread-24] INFO  org.dapnet.core.cluster.MembershipListener - Starting merge process
10:14:55.094 [Thread-24] INFO  org.dapnet.core.cluster.MembershipListener - Node is in majorSubgroup: Nothing to be done
10:14:55.094 [Thread-24] INFO  org.dapnet.core.cluster.MembershipListener - Finished merge process
10:14:55.094 [Thread-24] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of aprs.db0sda from UNKNOWN to ONLINE
10:14:55.094 [Thread-24] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
10:14:55.117 [Thread-24] INFO  org.dapnet.core.model.State - Successfully wrote state to file

**Comment by dh3wr** [comment]
Ist im experimental nicht mehr aufgetreten
