### ISSUE TITLE
Funkrufmaster Problem beim Starten

### ISSUE THREAD

**Issue by stephensworld** [DecentralizedAmateurPagingNetwork/Core#39]
Hi,

ich bekomme folgende Ausgabe beim starten des Funkrufmasters.

`12:18:27.828 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNET_CORE Version 0.9.3.1...
12:18:27.830 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
12:18:27.897 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
12:18:36.085 [Thread-1] INFO  org.dapnet.core.cluster.MembershipListener - New View: [raspberry.db0rta|14253] (5) [raspberry.db0rta, db0rta, db0wa, db0sda, dl4ste]
12:18:36.154 [Thread-1] INFO  org.dapnet.core.cluster.MembershipListener - Changed status of dl4ste from SUSPENDED to ONLINE
12:18:36.154 [Thread-1] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
12:18:36.183 [Thread-1] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:18:37.548 [Incoming-2,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.cluster.MessageListener - Receiving State from other Node
12:18:37.702 [Incoming-2,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:18:37.703 [Incoming-2,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.cluster.MessageListener - State successfully received
12:18:37.703 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
12:18:38.328 [main] FATAL org.dapnet.core.rest.RestManager - Starting RestApi failed
12:18:38.328 [main] ERROR org.dapnet.core.rest.RestManager - catching
javax.ws.rs.ProcessingException: IOException thrown when creating the JDK HttpServer.
	at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:125) ~[jersey-container-jdk-http-2.0.jar:?]
	at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:79) ~[jersey-container-jdk-http-2.0.jar:?]
	at org.dapnet.core.rest.RestManager.startServer(RestManager.java:48) [DAPNET_CORE.jar:?]
	at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:47) [DAPNET_CORE.jar:?]
	at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:104) [DAPNET_CORE.jar:?]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_111]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_111]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_111]
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100) ~[?:1.8.0_111]
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50) ~[?:1.8.0_111]
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35) ~[?:1.8.0_111]
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130) ~[?:1.8.0_111]
	at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:121) ~[jersey-container-jdk-http-2.0.jar:?]
	... 4 more
12:18:38.331 [main] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNET_CORE...
12:18:38.331 [main] INFO  org.dapnet.core.transmission.TransmitterDeviceManager - Successfully disconnected from all Transmitters
12:18:38.342 [Incoming-1,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:18:38.343 [Incoming-1,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
12:18:38.343 [Incoming-1,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.cluster.RpcListener - UpdateNodeStatus dl4ste to SUSPENDED: OK
12:18:39.360 [main] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:18:39.360 [main] ERROR org.dapnet.core.rest.RestManager - Stopping RestApi failed`

Vielleicht kann mir Jemand helfen.

 java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Vielen Dank

Gruß
Stephan

**Comment by dh3wr** [comment]
Hast du schon etwas auf dem API-Port laufen? Einen anderen Dienst? Z.B. einen Proxy?

**Comment by dh3wr** [comment]
Hier steht es ja ava.net.BindException: Address already in use at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]

**Comment by stephensworld** [comment]
Jetzt läufts :-)
Gab Kollisionen mit dem APRS Server aprsc

`12:45:54.957 [Thread-1] INFO  org.dapnet.core.cluster.MembershipListener - New View: [raspberry.db0rta|14270] (6) [raspberry.db0rta, db0rta, db0wa, db0sda, dl4ste, dl4ste]
12:45:55.002 [Thread-1] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
12:45:55.023 [Thread-1] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:45:56.602 [Incoming-1,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.cluster.MessageListener - Receiving State from other Node
12:45:56.654 [VERIFY_SUSPECT.TimerThread,DAPNET0.9.3.1,dl4ste] WARN  org.dapnet.core.cluster.MembershipListener - Node dl4ste is suspected
12:45:56.784 [Incoming-1,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:45:56.784 [Incoming-1,DAPNET0.9.3.1,dl4ste] INFO  org.dapnet.core.cluster.MessageListener - State successfully received
12:45:56.785 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
12:45:57.350 [Thread-2] INFO  org.dapnet.core.cluster.MembershipListener - New View: [raspberry.db0rta|14271] (5) [raspberry.db0rta, db0rta, db0wa, db0sda, dl4ste]
12:45:57.351 [Thread-2] INFO  org.dapnet.core.cluster.ClusterManager - Cluster has Quorum
12:45:57.356 [main] INFO  org.dapnet.core.rest.RestManager - RestApi successfully started
12:45:57.360 [main] INFO  org.dapnet.core.DAPNETCore - Starting SchedulerManager
12:45:57.396 [Thread-2] INFO  org.dapnet.core.model.State - Successfully wrote state to file
12:45:57.473 [main] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully started
12:45:57.473 [main] INFO  org.dapnet.core.DAPNETCore - DAPNETCore started
Enter "stop" to quit
`

**Comment by dh3wr** [comment]
Vielleicht kann man eine etwas leichter lesbare Fehlermeldung erzeugen? Marvin?

**Comment by MarvinMenzerath** [comment]
Vorher sah der Log so aus:
```
14:11:34.141 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
14:11:35.006 [main] FATAL org.dapnet.core.rest.RestManager - Starting RestApi failed
14:11:35.006 [main] ERROR org.dapnet.core.rest.RestManager - catching
javax.ws.rs.ProcessingException: IOException thrown when creating the JDK HttpServer.
        at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:125) ~[jersey-container-jdk-http-2.0.jar:?]
        at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:79) ~[jersey-container-jdk-http-2.0.jar:?]
        at org.dapnet.core.rest.RestManager.startServer(RestManager.java:50) [DAPNET_CORE.jar:?]
        at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:47) [DAPNET_CORE.jar:?]
        at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:104) [DAPNET_CORE.jar:?]
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_111]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_111]
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:1.8.0_111]
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:1.8.0_111]
        at sun.net.httpserver.ServerImpl.<init>(Unknown Source) ~[?:1.8.0_111]
        at sun.net.httpserver.HttpServerImpl.<init>(Unknown Source) ~[?:1.8.0_111]
        at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(Unknown Source) ~[?:1.8.0_111]
        at com.sun.net.httpserver.HttpServer.create(Unknown Source) ~[?:1.8.0_111]
        at org.glassfish.jersey.jdkhttp.JdkHttpServerFactory.createHttpServer(JdkHttpServerFactory.java:121) ~[jersey-container-jdk-http-2.0.jar:?]
        ... 4 more
14:11:35.014 [main] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNET_CORE...
```

Und jetzt so:
```
14:14:31.535 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
14:14:32.239 [main] FATAL org.dapnet.core.rest.RestManager - Starting RestApi failed
14:14:32.240 [main] FATAL org.dapnet.core.rest.RestManager - Address already in use
14:14:32.240 [main] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNET_CORE...
```

Sollte eine andere Exception als eine `BindException` fliegen, dann wird wie zuvor der StackTrace angezeigt.
