### ISSUE TITLE
nach erfolgreichem STOP kein start mehr möglich

### ISSUE THREAD

**Issue by rtausend** [DecentralizedAmateurPagingNetwork/Core#42]
Hallo zusammen,

ich habe meinen dapnet server mit STOP angehalten und gewartet bis sich die java selbst beendet hat.
Danach habe ich einen Neustart versucht, leider ohne Erfolg. Erst nach löschen der data und knownhosts verzeichnisse geht es wieder. Hier noch die Fehlermeldung beim start:

root@raspberry:/opt/dapnet# java -jar /opt/dapnet/DAPNET_CORE.jar
12:11:15.826 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNET_CORE Version 0.9.3.2...
12:11:15.847 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
12:11:17.199 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
root@raspberry:/opt/dapnet# java -jar /opt/dapnet/DAPNET_CORE.jar
12:13:04.149 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNET_CORE Version 0.9.3.2...
12:13:04.170 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
12:13:05.517 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateExpression(ResourceBundleMessageInterpolator.java:341)
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolateMessage(ResourceBundleMessageInterpolator.java:279)
        at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.interpolate(ResourceBundleMessageInterpolator.java:182)
        at org.hibernate.validator.internal.engine.ValidationContext.interpolate(ValidationContext.java:362)
        at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolation(ValidationContext.java:271)
        at org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolations(ValidationContext.java:232)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:291)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:133)
        at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:91)
        at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:83)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:547)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:487)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:451)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:403)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:723)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:617)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:412)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:206)
        at org.dapnet.core.cluster.ClusterManager.initState(ClusterManager.java:122)
        at org.dapnet.core.cluster.ClusterManager.<init>(ClusterManager.java:70)
        at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:44)
        at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:104)
Caused by: javax.el.ELException: Fail to load implementation class org.apache.el.ExpressionFactoryImpl
        at javax.el.ExpressionFactory.loadExpressionFactoryImplClass(ExpressionFactory.java:140)
        at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:60)
        at javax.el.ExpressionFactory.newInstance(ExpressionFactory.java:56)
        at org.hibernate.validator.internal.engine.messageinterpolation.InterpolationTerm.<clinit>(InterpolationTerm.java:59)
        ... 22 more
Caused by: java.lang.ClassNotFoundException: org.apache.el.ExpressionFactoryImpl
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at org.apache.geronimo.osgi.locator.ProviderLocator.loadClass(ProviderLocator.java:195)
        at javax.el.ExpressionFactory.loadExpressionFactoryImplClass(ExpressionFactory.java:135)
        ... 25 more
root@raspberry:/opt/dapnet#

Gruß Robert

**Comment by DanielSialkowski** [comment]
Hallo @rtausend,
sieht für mich aus als wenn eine Exception in den Tiefen von der hibernate libary geworfen wird, die für die Validierung zuständig ist. Vor einigen Monaten hatten wir bereits ein ähnliches Problem und damals waren falsch codierte Zeichen in der state.json der Grund. Ich weiß nicht, ob sich da in letzter Zeit etwas geändert hat. Hast du eventuell noch die alte state.json, die die Exception geworfen hat? Wäre gut, wenn man herausfinden könnte über welches Interface sich die Kodierungsfehler einschleichen. Prinzipiell sollten nämlich eigentlich Sonderzeichen kein Problem darstellen...

**Comment by rtausend** [comment]
Hallo Daniel,

nein, die state.json hab ich leider nicht mehr.

Den Fehler an sich hatte ich auch länger nicht mehr. Allerdings lässt sicher der Server mit stop fast nie richtig runterfahren, selbst wenn man mehrere Minuten wartet ;(

**Comment by dh3wr** [comment]
Das Problem ist im experimental branch gelößt

**Comment by dh3wr** [comment]
Vielleicht kann man in der Exception die zu beanstandende Stelle ausgeben? Würde das Tracking erleichtern

**Comment by Taronyu** [comment]
Stutzig macht mich ja Folgendes: Caused by: java.lang.ClassNotFoundException: org.apache.el.ExpressionFactoryImpl

Das hört sich für mich eher danach an, als ob der eine Dependency nicht finden kann.

**Comment by Taronyu** [comment]
Tritt das Problem auch mit dem neuen Core auf? Falls nein würde ich das hier schließen.

**Comment by dh3wr** [comment]
Nicht nochmal da gewesen.
