### ISSUE TITLE
Netty Exception

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#70]
````
14:11:03.446 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.transmission.ServerHandler - Exception in server handler.
java.io.IOException: Die Wartezeit für die Verbindung ist abgelaufen
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_121]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_121]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_121]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_121]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_121]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.1.8.Final.jar:4.1.8.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
14:11:03.453 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
14:11:03.453 [nioEventLoopGroup-3-2] WARN  org.dapnet.core.transmission.ServerHandler - Client has 62 pending acks.
14:11:03.455 [Incoming-1,DAPNET1.1.2.0,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus dm0max: OK
````

**Comment by Taronyu** [comment]
Ist das eine native Verbindung oder ging das über den Proxy? Das ist ein Socket Read Timeout, der hat da keine Antwort erhalten.

**Comment by dh3wr** [comment]
nativ. Wobei der entsprechende Mensch auch die ganze Zeit versuchte, REST API Anfragen an Port 43434 zu schicken. Das hat den Core auch schon 2 Mal kommentarlos beendet.

**Comment by dh3wr** [comment]
Ich habe jetzt in der Firewall die Anfragen erstmal ausgesperrt.

**Comment by Taronyu** [comment]
Das ist natürlich nicht gerade optimal, dass man den Core per REST abschießen kann. Wenn es eine Exception gab, dann müsste der das eigentlich geloggt haben.

**Comment by dh3wr** [comment]
Ist nicht mehr vorgekommen. Wir sollten trotzdem mal den Senderport auf DOS-Immulität testen

**Comment by Taronyu** [comment]
Ich hatte den schon mal mit JSON Requests bombadiert, ohne einen Absturz provozieren zu können. Der prüft ja die Welcome Message und macht dann die Verbindung zu. So richtig nachvollziehen kann ich nicht, was da passiert ist.

**Comment by dh3wr** [comment]
Vielleicht war's auch was anderes...
