### ISSUE TITLE
Exception main.rubricNameTransmissionJob

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#74]
Trat einmal auf mit der 1.1.3.0-SNAPSHOT 7fd2360007a37f4963a2954c56428d174e32a8c2

````
19:58:40.559 [Incoming-2,DAPNET1.1.3.0-SNAPSHOT,db0wa] INFO  org.dapnet.core.cluster.RpcListener - PutNode Node{status=SUSPENDED, name='dl4ste'}: OK
19:58:50.546 [INT-2,DAPNET1.1.3.0-SNAPSHOT,db0wa] WARN  org.jgroups.protocols.TCP - JGRP000012: discarded message from different cluster DAPNET1.1.2.0 (our cluster is DAPNET1.1.3.0-SNAPSHOT). Sender was dl4ste
20:00:00.013 [DefaultQuartzScheduler_Worker-2] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to all connected transmitters.
20:00:15.011 [DefaultQuartzScheduler_Worker-3] ERROR org.quartz.core.JobRunShell - Job main.rubricNameTransmissionJob threw an unhandled Exception:
java.lang.NoSuchMethodError: org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList;
        at org.dapnet.core.transmission.TransmissionManager.handleRubric(TransmissionManager.java:57) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.scheduler.RubricNameTransmissionJob.execute(RubricNameTransmissionJob.java:36) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
20:00:15.032 [DefaultQuartzScheduler_Worker-3] ERROR org.quartz.core.ErrorLogger - Job (main.rubricNameTransmissionJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
Caused by: java.lang.NoSuchMethodError: org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList;
        at org.dapnet.core.transmission.TransmissionManager.handleRubric(TransmissionManager.java:57) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.scheduler.RubricNameTransmissionJob.execute(RubricNameTransmissionJob.java:36) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.3.jar:?]
        ... 1 more
````

**Comment by dh3wr** [comment]
Tritt auch mehrfach auf
````
20:19:25.996 [Incoming-1,DAPNET1.1.3.0-SNAPSHOT,db0sda] ERROR org.dapnet.core.cluster.RpcListener - PostCall CallSign{name='dh3wr'}: no response
20:19:46.136 [nioEventLoopGroup-3-3] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
20:19:46.137 [Incoming-1,DAPNET1.1.3.0-SNAPSHOT,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus dl2ic_debug: OK
20:19:49.238 [INT-2,DAPNET1.1.3.0-SNAPSHOT,db0sda] WARN  org.jgroups.protocols.TCP - JGRP000012: discarded message from different cluster DAPNET1.1.2.0 (our cluster is DAPNET1.1.3.0-SNAPSHOT). Sender was dl4ste (received 4 identical messages from dl4ste in the last 64736 ms)
20:20:00.001 [DefaultQuartzScheduler_Worker-3] INFO  org.dapnet.core.transmission.TransmissionManager - Time sent to all connected transmitters.
20:20:01.130 [nioEventLoopGroup-3-4] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /89.0.227.188:53416
20:20:01.597 [Incoming-1,DAPNET1.1.3.0-SNAPSHOT,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus dl2ic_debug: OK
20:20:15.001 [DefaultQuartzScheduler_Worker-4] ERROR org.quartz.core.JobRunShell - Job main.rubricNameTransmissionJob threw an unhandled Exception:
java.lang.NoSuchMethodError: org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList;
        at org.dapnet.core.transmission.TransmissionManager.handleRubric(TransmissionManager.java:57) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.scheduler.RubricNameTransmissionJob.execute(RubricNameTransmissionJob.java:36) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
20:20:15.001 [DefaultQuartzScheduler_Worker-4] ERROR org.quartz.core.ErrorLogger - Job (main.rubricNameTransmissionJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
Caused by: java.lang.NoSuchMethodError: org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList;
        at org.dapnet.core.transmission.TransmissionManager.handleRubric(TransmissionManager.java:57) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.scheduler.RubricNameTransmissionJob.execute(RubricNameTransmissionJob.java:36) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.3.jar:?]
        ... 1 more
````

**Comment by Taronyu** [comment]
Haben alle Knoten im Node dieselbe Version? Da schlägt ein RPC fehl und ich habe die Methodensignatur geändert. Das passt nicht mit alten Knoten zusammen. Das kann auch weitere Fehler nach sich ziehen, beispielsweise beim Anlegen von Ressourcen.

**Comment by dh3wr** [comment]
Aha, nein einer spielt noch auf der Alten. Dann firewalle ich den mal.

**Comment by dh3wr** [comment]
Ich habe das Subnetz von dl4ste mal geblockt. Mal sehen, ob noch was kommt.

**Comment by dh3wr** [comment]
Immer noch, aber interessanter Weise ist der Update Transmitter Status jetzt OK **_ADMIN_**  ? Das ADMIN war woher nicht da...
````
22:55:03.109 [Incoming-1,DAPNET1.1.3.0-SNAPSHOT,db0sda] INFO  org.dapnet.core.cluster.RpcListener - UpdateTransmitterStatus dl6fz: OK
ADMIN
22:55:08.812 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Accepted new connection from /44.225.164.2:56944
22:55:08.813 [nioEventLoopGroup-3-2] ERROR org.dapnet.core.transmission.ServerHandler - Closing connection: Invalid welcome message format:
22:55:08.813 [nioEventLoopGroup-3-2] INFO  org.dapnet.core.transmission.ServerHandler - Connection closed.
22:55:15.002 [DefaultQuartzScheduler_Worker-3] ERROR org.quartz.core.JobRunShell - Job main.rubricNameTransmissionJob threw an unhandled Exception:
java.lang.NoSuchMethodError: org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList;
        at org.dapnet.core.transmission.TransmissionManager.handleRubric(TransmissionManager.java:57) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.scheduler.RubricNameTransmissionJob.execute(RubricNameTransmissionJob.java:36) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
22:55:15.007 [DefaultQuartzScheduler_Worker-3] ERROR org.quartz.core.ErrorLogger - Job (main.rubricNameTransmissionJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.2.3.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.2.3.jar:?]
Caused by: java.lang.NoSuchMethodError: org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList;
        at org.dapnet.core.transmission.TransmissionManager.handleRubric(TransmissionManager.java:57) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.scheduler.RubricNameTransmissionJob.execute(RubricNameTransmissionJob.java:36) ~[dapnet-core-1.1.3.0-SNAPSHOT.jar:1.1.3.0-SNAPSHOT]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.3.jar:?]
        ... 1 more
````

**Comment by Taronyu** [comment]
Kannst du bitte mal mit `mvn clean package` bauen? Eventuell hat der noch eine alte Datei verwendet.

**Comment by dh3wr** [comment]
So, neu gebaut und läuft. Wenn ich nichts mehr sehe, dann können wir das zumachen.

**Comment by Taronyu** [comment]
Ok, hoffen wir mal, dass sich das erledigt hat :)

**Comment by dh3wr** [comment]
Ist weg

**Comment by Taronyu** [comment]
Der kann den Remote Procedure Call nicht absetzen, da es die Methode mit der angeforderten Signatur nicht gibt. Der Aufruf erfolgt mittels Reflection, da läuft irgendwo doch noch was altes. Auch `mvn clean package` gemacht?

Die alte Signatur sah so aus:
```ArrayList<TransmitterGroup> getTransmitterGroups() throws Exception```
Und die neue so:
```Collection<TransmitterGroup> getTransmitterGroups() throws Exception```
Und wie man hier sehen kann, versucht der es mit der alten Version:
```org.dapnet.core.model.Rubric.getTransmitterGroups()Ljava/util/ArrayList```

**Comment by dh3wr** [comment]
Ich versuche mal rauszubekommen, wer das ist.. Danke

**Comment by Taronyu** [comment]
Das muss der Knoten sein, von dem du das Log hast. Entgegen meiner vorherigen Aussage ist hier kein Remote Procedure Call involviert, das ist ein rein lokales Problem.

**Comment by dh3wr** [comment]
ok, es war db0wa. Taucht nicht mehr auf. Das gefährliche an mvn clean ist, dass es wohl auch die target/config und target/data Verzeichnisse löscht. Vielleicht kann man da noch was in den Meta-Files ändern, dass man dies nicht tut oder noch besser, die Jar aus dem target in ein richtiges working dir kopieren. Dann muss aber das libs-Dir ebenfalls mit, oder? Bzw. kann man mit mvn package auch direkt ein großers jar mit allen Abhängigkeiten machen? Dann packt man das einfach mit cp woanders hin und startet von da.

**Comment by Taronyu** [comment]
Theoretisch kann man ein jar mit allen Dependencies machen, beim Proxy ist das auch so konfiguriert. Bei der Menge an Dependencies, die vom Core benötigt werden, wird das aber nicht empfohlen. Theoretisch können Informationen aus den einzelnen jars verloren gehen, was dann zu Problemen führen kann. Abgesehen davon müsste man auch die Lizenzen berücksichtigen, ob man das überhaupt darf.

Es ist auch eigentlich gar nicht vorgesehen, dass man die Binaries aus dem target Verzeichnis startet. Da das bei laufender Entwicklung aber doch ziemlich nervig sein kann, habe ich einen Workaround: Du kannst im Hauptverzeichnis ein Verzeichnis "local" anlegen, in das du den config und data Ordner kopierst. Das Verzeichnis ist auch per gitignore vom Repository ausgeschlossen. In dem Verzeichnis muss man dann ein Skript anlegen, das die jar aus dem target Ordner in einer passenden Umgebung startet. So kann man `mvn clean package` ausführen ohne config/data zu verlieren.

**Comment by dh3wr** [comment]
Habe ich umgesetzt. Danke.

**Comment by Taronyu** [comment]
Warum hast du das denn jetzt mehrfach in die gitignore eingetragen? Ich hatte doch gesagt, dass local schon drinnen steht.

**Comment by Taronyu** [comment]
Ich habe mal deine Beispielconfigs in das Archiv gepackt, das bei package erzeugt wird.

**Comment by dh3wr** [comment]
@Taronyu Meine Dummheit, hätte ich besser lesen sollen. War nicht klar, dass es schon drin war. Sorry

**Comment by Taronyu** [comment]
Kein Problem, wollte auch nicht motzen. Ich habe das schon wieder umgebaut.

**Comment by dh3wr** [comment]
Schon gesehen. Alles gut.
