### ISSUE TITLE
Core läuft nicht nach Build mit intelliJ IDEA

### ISSUE THREAD

**Issue by phl0** [DecentralizedAmateurPagingNetwork/Core#78]
Nach erfolgreichem Build mittels intelliJ IDEA Community Edition will der Core nicht laufen. Fehlermeldung:

```
/usr/lib/jvm/java-8-oracle/bin/java -Didea.launcher.port=7533 -Didea.launcher.bin.path=/opt/intellij-idea-community/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/opt/Core/target/classes:/home/florian/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/florian/.m2/repository/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.jar:/home/florian/.m2/repository/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.jar:/home/florian/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.7/log4j-slf4j-impl-2.7.jar:/home/florian/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/home/florian/.m2/repository/org/hibernate/hibernate-validator/5.3.4.Final/hibernate-validator-5.3.4.Final.jar:/home/florian/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/florian/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar:/home/florian/.m2/repository/com/fasterxml/classmate/1.3.1/classmate-1.3.1.jar:/home/florian/.m2/repository/javax/el/javax.el-api/2.2.4/javax.el-api-2.2.4.jar:/home/florian/.m2/repository/org/glassfish/web/javax.el/2.2.4/javax.el-2.2.4.jar:/home/florian/.m2/repository/org/glassfish/jersey/core/jersey-client/2.25/jersey-client-2.25.jar:/home/florian/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:/home/florian/.m2/repository/org/glassfish/jersey/core/jersey-common/2.25/jersey-common-2.25.jar:/home/florian/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.25/jersey-guava-2.25.jar:/home/florian/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar:/home/florian/.m2/repository/org/glassfish/hk2/hk2-api/2.5.0-b30/hk2-api-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/hk2-utils/2.5.0-b30/hk2-utils-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.5.0-b30/aopalliance-repackaged-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/external/javax.inject/2.5.0-b30/javax.inject-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/hk2-locator/2.5.0-b30/hk2-locator-2.5.0-b30.jar:/home/florian/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:/home/florian/.m2/repository/org/glassfish/jersey/core/jersey-server/2.25/jersey-server-2.25.jar:/home/florian/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.25/jersey-media-jaxb-2.25.jar:/home/florian/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:/home/florian/.m2/repository/org/jgroups/jgroups/3.6.11.Final/jgroups-3.6.11.Final.jar:/home/florian/.m2/repository/org/quartz-scheduler/quartz/2.2.3/quartz-2.2.3.jar:/home/florian/.m2/repository/c3p0/c3p0/0.9.1.1/c3p0-0.9.1.1.jar:/home/florian/.m2/repository/org/quartz-scheduler/quartz-jobs/2.2.3/quartz-jobs-2.2.3.jar:/home/florian/.m2/repository/org/glassfish/jersey/containers/jersey-container-jdk-http/2.25/jersey-container-jdk-http-2.25.jar:/home/florian/.m2/repository/org/glassfish/jersey/containers/jersey-container-grizzly2-http/2.25/jersey-container-grizzly2-http-2.25.jar:/home/florian/.m2/repository/org/glassfish/grizzly/grizzly-http-server/2.3.28/grizzly-http-server-2.3.28.jar:/home/florian/.m2/repository/org/glassfish/grizzly/grizzly-http/2.3.28/grizzly-http-2.3.28.jar:/home/florian/.m2/repository/org/glassfish/grizzly/grizzly-framework/2.3.28/grizzly-framework-2.3.28.jar:/home/florian/.m2/repository/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:/opt/intellij-idea-community/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain org.dapnet.core.DAPNETCore
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.dapnet.core.DAPNETCore.<clinit>(DAPNETCore.java:48)
	... 3 more

Process finished with exit code 1
```

Bestimmt ein Fehler auf meiner Seite. Nur was mache ich falsch?

**Comment by phl0** [comment]
```
CORE_VERSION = DAPNETCore.class.getPackage().getImplementationVersion();
```
liefert offenbar: 

```
19:14:33.967 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNETCore Version null ...
```

**Comment by Taronyu** [comment]
Mir fallen momentan zwei Gründe ein, warum das nicht läuft: 1) Es ist kein Maven Projekt, 2) du startet das Projekt direkt aus der IDE heraus. Die Versionsnummer wird beim Bauen mit Maven in das jar Archiv geschrieben. IDEs starten die Projekte in der Regel aber direkt aus den kompilierten Klassen und nicht aus dem jar. Dann fehlt aber die Versionsnummer. Ich habe die jetzt mal auf "UNKNOWN" gesetzt, wenn der die nicht lesen kann. Dann sollte zumindest die NullPointerEx weg sein.

**Comment by phl0** [comment]
Beide Tatsachen treffen zu. Ich hatte es als "Application" direkt aus der intelliJ IDEA heraus gestartet. Somit war es auch kein maven Projekt. Bisher ging das. Ich versuche es mal in der IDE mit maven. Das kann die ja offensichtlich auch.

**Comment by phl0** [comment]
Mit dem fix aus https://github.com/DecentralizedAmateurPagingNetwork/Core/commit/faff3a14dee9947f221f539ad846f0721a31a5a3 startet es (wieder) als Application direkt aus der IDE:

```
/usr/lib/jvm/java-8-oracle/bin/java -Didea.launcher.port=7533 -Didea.launcher.bin.path=/opt/intellij-idea-community/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/opt/Core/target/classes:/home/florian/.m2/repository/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/florian/.m2/repository/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.jar:/home/florian/.m2/repository/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.jar:/home/florian/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.7/log4j-slf4j-impl-2.7.jar:/home/florian/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/home/florian/.m2/repository/org/hibernate/hibernate-validator/5.3.4.Final/hibernate-validator-5.3.4.Final.jar:/home/florian/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/florian/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar:/home/florian/.m2/repository/com/fasterxml/classmate/1.3.1/classmate-1.3.1.jar:/home/florian/.m2/repository/javax/el/javax.el-api/2.2.4/javax.el-api-2.2.4.jar:/home/florian/.m2/repository/org/glassfish/web/javax.el/2.2.4/javax.el-2.2.4.jar:/home/florian/.m2/repository/org/glassfish/jersey/core/jersey-client/2.25/jersey-client-2.25.jar:/home/florian/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar:/home/florian/.m2/repository/org/glassfish/jersey/core/jersey-common/2.25/jersey-common-2.25.jar:/home/florian/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.25/jersey-guava-2.25.jar:/home/florian/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar:/home/florian/.m2/repository/org/glassfish/hk2/hk2-api/2.5.0-b30/hk2-api-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/hk2-utils/2.5.0-b30/hk2-utils-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.5.0-b30/aopalliance-repackaged-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/external/javax.inject/2.5.0-b30/javax.inject-2.5.0-b30.jar:/home/florian/.m2/repository/org/glassfish/hk2/hk2-locator/2.5.0-b30/hk2-locator-2.5.0-b30.jar:/home/florian/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:/home/florian/.m2/repository/org/glassfish/jersey/core/jersey-server/2.25/jersey-server-2.25.jar:/home/florian/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.25/jersey-media-jaxb-2.25.jar:/home/florian/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:/home/florian/.m2/repository/org/jgroups/jgroups/3.6.11.Final/jgroups-3.6.11.Final.jar:/home/florian/.m2/repository/org/quartz-scheduler/quartz/2.2.3/quartz-2.2.3.jar:/home/florian/.m2/repository/c3p0/c3p0/0.9.1.1/c3p0-0.9.1.1.jar:/home/florian/.m2/repository/org/quartz-scheduler/quartz-jobs/2.2.3/quartz-jobs-2.2.3.jar:/home/florian/.m2/repository/org/glassfish/jersey/containers/jersey-container-jdk-http/2.25/jersey-container-jdk-http-2.25.jar:/home/florian/.m2/repository/org/glassfish/jersey/containers/jersey-container-grizzly2-http/2.25/jersey-container-grizzly2-http-2.25.jar:/home/florian/.m2/repository/org/glassfish/grizzly/grizzly-http-server/2.3.28/grizzly-http-server-2.3.28.jar:/home/florian/.m2/repository/org/glassfish/grizzly/grizzly-http/2.3.28/grizzly-http-2.3.28.jar:/home/florian/.m2/repository/org/glassfish/grizzly/grizzly-framework/2.3.28/grizzly-framework-2.3.28.jar:/home/florian/.m2/repository/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:/opt/intellij-idea-community/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain org.dapnet.core.DAPNETCore
07:45:22.466 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNETCore Version UNKNOWN ...
07:45:22.469 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
07:45:22.537 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
07:45:22.571 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.3.4.Final
07:45:22.661 [main] WARN  org.dapnet.core.cluster.ClusterManager - Creating new empty State
07:45:28.242 [Thread-3] INFO  org.dapnet.core.cluster.MembershipListener - New View: [THIS_IS_YOUR_CALLSIGN|0] (1) [THIS_IS_YOUR_CALLSIGN]
07:45:28.245 [main] WARN  org.dapnet.core.cluster.ChannelListener - Creating new Cluster: Check configuration and restart in case you want to join an existing one
07:45:28.248 [main] INFO  org.dapnet.core.cluster.ChannelListener - Creating first node
07:45:28.287 [Thread-3] INFO  org.dapnet.core.model.State - Successfully wrote state to file
07:45:30.510 [Incoming-1,DAPNETUNKNOWN,THIS_IS_YOUR_CALLSIGN] WARN  org.dapnet.core.cluster.RpcListener - PutNode Node{status=ONLINE, name='THIS_IS_YOUR_CALLSIGN'}: VALIDATION_ERROR
07:45:30.514 [main] ERROR org.dapnet.core.cluster.ClusterManager - Response: [sender=THIS_IS_YOUR_CALLSIGNvalue=VALIDATION_ERROR, received=true, suspected=false]

07:45:30.514 [main] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
07:45:30.514 [main] FATAL org.dapnet.core.cluster.ChannelListener - First node could not been created
07:45:30.514 [main] INFO  org.dapnet.core.DAPNETCore - Stopping DAPNETCore ...
07:45:30.514 [main] INFO  org.dapnet.core.DAPNETCore - DAPNETCore stopped
07:45:30.514 [main] INFO  org.dapnet.core.cluster.ChannelListener - Creating first user
07:45:30.544 [Incoming-1,DAPNETUNKNOWN,THIS_IS_YOUR_CALLSIGN] INFO  org.dapnet.core.cluster.RpcListener - PutUser User{name='admin'}: OK
07:45:30.545 [main] INFO  org.dapnet.core.cluster.ChannelListener - First user successfully updated
07:45:30.546 [main] INFO  org.dapnet.core.DAPNETCore - Starting SchedulerManager
07:45:30.694 [main] INFO  org.dapnet.core.scheduler.SchedulerManager - SchedulerManager successfully started
07:45:30.694 [main] INFO  org.dapnet.core.DAPNETCore - Starting RestManager
07:45:31.775 [main] INFO  org.dapnet.core.rest.RestManager - RestApi successfully started
07:45:31.776 [main] INFO  org.dapnet.core.DAPNETCore - Starting Transmitter Server
07:45:31.778 [main] INFO  org.dapnet.core.DAPNETCore - DAPNETCore started
07:45:31.914 [Thread-4] INFO  org.dapnet.core.transmission.Server - Server started on port: 43434
```

**Comment by Taronyu** [comment]
Du musst bei der Variante allerdings beachten, dass die Version auf "UNKNOWN" gesetzt wird. Ich bin mir gerade nicht sicher, ob wir irgendwo die Version prüfen, das könnte dann zu Problemen führen.

**Comment by phl0** [comment]
Japp, das ist tatsächlich der Fall. Aber immerhin läuft der build damit.
Ich kann gerne mal einen Client dran hängen und das prüfen. Der Core
selbst läuft damit jedenfalls ohne erkennbare Probleme.

**Comment by Taronyu** [comment]
Die Clients dürften da kein Problem mit haben, die sehen die Core-Version nicht. Ich meinte eher, dass das Clustering betroffen sein könnte. Jedenfalls gut zu wissen, dass es nun auch über die IDE läuft. Das hatte ich selbst nämlich noch gar nicht ausprobiert 😃

**Comment by phl0** [comment]
Wer betreibt denn den/einen experimental Master? Ich könnte dort mal ein
Peering versuchen.

**Comment by Taronyu** [comment]
Hmm, wüsste ich jetzt nicht. Für die Praxis ist das denke ich aber eh irrelevant, da man den Core im Betrieb ja über die jar startet.
