### ISSUE TITLE
Core stürzt immer wieder ab

### ISSUE THREAD

**Issue by rtausend** [DecentralizedAmateurPagingNetwork/Core#79]
Hallo zusammen,

seit der letzten Version stürzt der Core auf meinem Raspberry immer wieder ab, hier aus dem Log:

2017-03-19 14:37:05,798 INFO org.dapnet.core.cluster.MessageListener [Incoming-1,DAPNET1.1.3.0-SNAPSHOT,raspberry.db0rta] State successfully received
2017-03-19 14:37:05,802 INFO org.dapnet.core.DAPNETCore [Thread-1] Stopping DAPNETCore ...
2017-03-19 14:37:05,810 ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution [Thread-1] Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:113) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1010) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:610) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234) [netty-all-4.1.9.Final.jar:4.1.9.Final]
        at org.dapnet.core.transmission.Server.close(Server.java:56) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.stop(DAPNETCore.java:90) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.access$100(DAPNETCore.java:32) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore$1.run(DAPNETCore.java:128) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
2017-03-19 14:37:05,831 ERROR org.dapnet.core.DAPNETCore [Thread-1] Failed to close the device server.
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1007) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:610) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
        at org.dapnet.core.transmission.Server.close(Server.java:56) ~[DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.stop(DAPNETCore.java:90) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.access$100(DAPNETCore.java:32) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore$1.run(DAPNETCore.java:128) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
2017-03-19 14:37:05,849 INFO org.dapnet.core.rest.RestManager [Thread-1] RestApi successfully stopped
2017-03-19 14:37:05,851 INFO org.dapnet.core.scheduler.SchedulerManager [Thread-1] SchedulerManager successfully stopped
2017-03-19 14:37:05,857 ERROR org.dapnet.core.cluster.ClusterManager [Thread-1] Catching
java.lang.IllegalStateException: channel is not connected
        at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.down(MessageDispatcher.java:682) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RequestCorrelator.sendRequest(RequestCorrelator.java:172) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.GroupRequest.sendRequest(GroupRequest.java:325) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.GroupRequest.sendRequest(GroupRequest.java:76) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.Request.execute(Request.java:67) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.MessageDispatcher.cast(MessageDispatcher.java:373) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.MessageDispatcher.cast(MessageDispatcher.java:386) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.MessageDispatcher.castMessage(MessageDispatcher.java:272) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RpcDispatcher.callRemoteMethods(RpcDispatcher.java:153) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RpcDispatcher.callRemoteMethods(RpcDispatcher.java:122) ~[jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.dapnet.core.cluster.ClusterManager.handleStateOperation(ClusterManager.java:218) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.cluster.ClusterManager.updateNodeStatus(ClusterManager.java:233) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.cluster.ClusterManager.handleDisconnectedFromAllTransmitters(ClusterManager.java:269) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.transmission.TransmitterManager.disconnectFromAll(TransmitterManager.java:135) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.cluster.ClusterManager.stop(ClusterManager.java:147) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.stop(DAPNETCore.java:105) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.access$100(DAPNETCore.java:32) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]
        at org.dapnet.core.DAPNETCore$1.run(DAPNETCore.java:128) [DAPNET_CORE.jar:1.1.3.0-SNAPSHOT]

**Comment by Taronyu** [comment]
Okay, das ist interessant. Nach dem Empfang des States schaltet sich der Core ab ("Stopping Core"), der sagt aber nicht warum. Der Fehler, der danach kommt, scheint durch das Stoppen ausgelöst zu werden. Hast du davor noch irgendetwas im Log? Ich habe mal im master Branch ein sync auf die Event Loop Groups für netty beim shutdown gesetzt, bezweifel aber, dass dies die Lösung ist. Wie gesagt, interessant wäre, warum der Core stoppen will.

**Comment by Taronyu** [comment]
Ist das Problem auch mit einer neueren Version aufgetreten?

**Comment by Taronyu** [comment]
Leider keine weitere Rückmeldung erhalten. Falls das Problem doch noch einmal auftritt, einfach wieder das Issue öffnen.
