### ISSUE TITLE
Fehler bei Umstieg von 1.1.3.0-SNAPSHOT auf 1.1.3.0 Release

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#83]
Die State,json scheint sich in ihren Aufbau geändert zu haben.
````
rwth-afu@dapnet:/opt/dapnet/Core/local$ java -Dlog4j.configurationFile=../local/config/LogSettings_REST.xml -jar ../target/dapnet-core-1.1.3.0.jar
10:23:46.262 [main] INFO  org.dapnet.core.DAPNETCore - Starting DAPNETCore Version 1.1.3.0 ...
10:23:46.264 [main] INFO  org.dapnet.core.DAPNETCore - Starting TransmissionManager
10:23:46.324 [main] INFO  org.dapnet.core.DAPNETCore - Starting Cluster
10:23:46.350 [main] INFO  org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.3.4.Final
10:23:46.583 [main] ERROR org.dapnet.core.cluster.ClusterManager - Failed to load state from file.
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 6155 column 26 path $.transmitters..connectedSince
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.0.jar:?]
        at org.dapnet.core.rest.GsonTypeAdapterFactory$GenericTypeAdapter.read(GsonTypeAdapterFactory.java:67) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:?]
        at org.dapnet.core.rest.GsonTypeAdapterFactory$GenericTypeAdapter.read(GsonTypeAdapterFactory.java:67) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:?]
        at org.dapnet.core.rest.GsonTypeAdapterFactory$GenericTypeAdapter.read(GsonTypeAdapterFactory.java:67) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?]
        at org.dapnet.core.model.State.readFromFile(State.java:108) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.cluster.ClusterManager.initState(ClusterManager.java:109) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.cluster.ClusterManager.<init>(ClusterManager.java:70) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:70) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:149) [dapnet-core-1.1.3.0.jar:1.1.3.0]
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 6155 column 26 path $.transmitters..connectedSince
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825) ~[gson-2.8.0.jar:?]
        at org.dapnet.core.rest.GsonTypeAdapterFactory$InstantTypeAdapter.read(GsonTypeAdapterFactory.java:108) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.rest.GsonTypeAdapterFactory$InstantTypeAdapter.read(GsonTypeAdapterFactory.java:90) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:?]
        ... 15 more
10:23:46.589 [main] WARN  org.dapnet.core.cluster.ClusterManager - Creating new empty State
````

**Comment by Taronyu** [comment]
Kannst du mir die Zeile 6155 +/- ein paar aus der betreffenden State.json mal zeigen?

**Comment by dh3wr** [comment]
Ja, moment, ich muss das nochmal neu starten, da sich die State.json schon wieder verändert hat.

**Comment by Taronyu** [comment]
Ich konnte das Problem bei mir bisher nicht nachstellen. Ich hatte die Serialisierung des Datums im Verdacht, das sieht aber in Ordnung aus.

**Comment by dh3wr** [comment]
Hier die Zeilen.
``com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5218 column 6 path $.news[0]``

````
5217:  "news": [
5218:    {
5219:      "text": "DM0MAX 438.7375     DB0BI  439,2500     DB0OWL 438,8000     DB0LH  439,1250",
5220:      "rubricName": "dm0max-r70cm",
5221:      "number": 1,
5222:      "timestamp": "Apr 10, 2017 12:01:01 AM",
5223:      "ownerName": "do7sk"
5224:    },
````

````
    {
      "text": "**NAGIOS** RECOVERY: DB0POC/Funkrufsender DB0POC is OK",
      "callSignNames": [
        "DF2ET"
      ],
      "transmitterGroupNames": [
        "test_N18"
      ],
      "emergency": false,
      "timestamp": "Apr 11, 2017 11:35:02 AM",
      "ownerName": "df2et"
    }
  ],
  "news": [
    {
      "text": "DM0MAX 438.7375     DB0BI  439,2500     DB0OWL 438,8000     DB0LH  439,1250",
      "rubricName": "dm0max-r70cm",
      "number": 1,
      "timestamp": "Apr 10, 2017 12:01:01 AM",
      "ownerName": "do7sk"
    },
    {
      "text": "DB0SA  438.6250 C77 DB0XXL 438,9250     DB0OWL 438,8000     DB0OZ  439,7750",
      "rubricName": "dm0max-r70cm",
      "number": 2,
      "timestamp": "Apr 10, 2017 12:01:01 AM",
      "ownerName": "do7sk"
    },
    {
      "text": "DM0MAX 145,7500     DB0WY  145,6500     DB0SA  145,6250 C67 DB0DOS 145,7125 C123",
      "rubricName": "dm0max-r2m",
      "number": 1,
      "timestamp": "Apr 10, 2017 12:01:02 AM",
      "ownerName": "do7sk"
    },
````

**Comment by Taronyu** [comment]
Oh ja, das sieht jetzt anders aus:
```
"rubrics": {
    "rwth-afu": {
      "name": "rwth-afu",
      "number": 12,
      "transmitterGroupNames": [
        "dl-nw",
        "dl-by"
      ],
      "label": "RWTH-AFU",
      "ownerNames": [
        "dh3wr"
      ]
    }
},
"news": {
    "rwth-afu": [
      {
        "text": "Test 1",
        "rubricName": "rwth-afu",
        "number": 1,
        "timestamp": "2017-04-11T10:29:43.217Z",
        "ownerName": "admin"
      }
    ]
}
```
Sofern die Rubriken noch so aussehen, kannst du mal testweise den ganzen News-Block entfernen? Der Core legt dann einen neuen mit der passenden Struktur an. Wenn es dann funktioniert, war das tatsächlich der Fehler. Kann man ggf. noch einmal ein Konvertierskript schreiben, das die bestehenden Einträge in das neue Format überführt.

**Comment by dh3wr** [comment]
ok, ich schau mal , ob ich das von Hand hinbekomme

**Comment by dh3wr** [comment]
habe die News von Hand gelöscht. Nun aber noch ein Problem bei den Transmittern
````
  "transmitters": {
    "dm0max": {
      "name": "dm0max",
      "authKey": "do7sk",
      "longitude": "8.70194444",
      "latitude": "52.2905556",
      "power": "10",
      "nodeName": "dm0max",
      "address": {
        "ip_addr": "127.0.0.1",
        "port": 59290
      },
      "timeSlot": "45CD",
      "ownerNames": [
        "do7sk"
      ],
      "deviceType": "UniPager-Audio",
      "deviceVersion": "0.5.1",
      "status": "ONLINE",
      "antennaAboveGroundLevel": 328,
      "antennaType": "OMNI",
      "antennaDirection": 0,
      "antennaGainDbi": 6.0,
      "usage": "WIDERANGE",
      "connectedSince": {
        "seconds": 1491424310,
        "nanos": 668000000
      }
````
``Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 5284 column 26 path $.transmitters..connectedSince``

Line 5284 ist die ``      "connectedSince": {``  Line

**Comment by Taronyu** [comment]
Schon, aber der Zeitstring sieht anders aus: `"2017-04-11T09:10:16.286Z"`. Du kannst das aber alles mit `null` ersetzen (dann ohne Anführungszeichen).

**Comment by dh3wr** [comment]
läuft jetzt nach manueller Anpassung

**Comment by Taronyu** [comment]
Schön :)

**Comment by dh3wr** [comment]
Jetzt nur noch auf allen Cores updaten...
