### ISSUE TITLE
Node Auth Keys werden ungültig

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#84]
Es ist nicht ganz klar, wann und warum, aber manchmal kann sich ein Core nicht mit dem Cluster verbinden:
````
10:32:45.742 [INT-2,DAPNET1.1.3.0-SNAPSHOT,db0sda] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node dl4ste failed: Wrong key
10:32:45.742 [INT-2,DAPNET1.1.3.0-SNAPSHOT,db0sda] WARN  org.jgroups.protocols.AUTH - db0sda: failed to validate AuthHeader (token: ClusterAuthentication) from dl4ste; dropping message
10:32:45.878 [INT-1,DAPNET1.1.3.0-SNAPSHOT,db0sda] WARN  org.dapnet.core.cluster.ClusterAuthentication - Authentication of Node dm0max failed: Unknown node
````
Wenn man dann in einem schon existierenden Core den AuthKey einfach neu setzt, dann geht es wieder.

Vielleicht können wir diese Hashing-Geschichte des Node-AuthKeys einfach rauswerfen? Wirklich nötig ist das nicht. Oder alternativ nach dem Fehler suchen.

**Comment by Taronyu** [comment]
Betrifft das "wrong key" nur den Knoten dl4ste?

Die andere Meldung "Unknown node" kommt jedenfalls nur wenn der Knoten nicht im State gefunden wird.

**Comment by dh3wr** [comment]
Nein, das taucht immer mal wieder auf, unabh. vom Knoten.

**Comment by Taronyu** [comment]
Die Passwortfunktion wird auch für die Benutzeraccounts verwendet. Wenn hier keine Probleme gemeldet wurden, dann liegt das wohl eher nicht an der Funktion selbst. Ich hatte jedenfalls bisher noch nie Probleme damit, mich anzumelden. Das spricht eigentlich dafür, dass der Fehler auf den Authentifizierungsprozess der Knoten beschränkt ist und man sich den noch einmal genau ansehen muss.

**Comment by Taronyu** [comment]
Eventuell hängt das auch mit #56 zusammen. Ich hatte beim Testen jetzt auch schon einmal ein Problem mit dem Austausch des States zwischen den Knoten, da gab es einen Serialisierungsfehler. Das gab allerdings auch einen fetten Stacktrace...

**Comment by dh3wr** [comment]
Das ein neu-Setzen des AuthKey beim Node, an den sich dl4ste versuchte anzumelden, die Fehlermeldung behob, ist wieder eingetreten:
````
17:34:56.857 [main] FATAL org.dapnet.core.cluster.ClusterManager - Could not connect to cluster.
java.lang.Exception: connecting to channel "DAPNET1.1.3.1-SNAPSHOT" failed
        at org.jgroups.JChannel._connect(JChannel.java:570) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.JChannel.connect(JChannel.java:294) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.JChannel.connect(JChannel.java:279) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.dapnet.core.cluster.ClusterManager.<init>(ClusterManager.java:98) [dapnet-core-1.1.3.1-SNAPSHOT.jar:1.1.3.1-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.start(DAPNETCore.java:71) [dapnet-core-1.1.3.1-SNAPSHOT.jar:1.1.3.1-SNAPSHOT]
        at org.dapnet.core.DAPNETCore.main(DAPNETCore.java:145) [dapnet-core-1.1.3.1-SNAPSHOT.jar:1.1.3.1-SNAPSHOT]
Caused by: java.lang.SecurityException: authentication failed
        at org.jgroups.protocols.pbcast.ClientGmsImpl.isJoinResponseValid(ClientGmsImpl.java:187) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.pbcast.ClientGmsImpl.installViewIfValidJoinRsp(ClientGmsImpl.java:153) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl.java:111) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:41) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.protocols.pbcast.GMS.down(GMS.java:1079) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:1039) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.JChannel.down(JChannel.java:790) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        at org.jgroups.JChannel._connect(JChannel.java:564) ~[jgroups-3.6.13.Final.jar:3.6.13.Final]
        ... 5 more
17:34:56.860 [main] FATAL org.dapnet.core.DAPNETCore - Failed to start DAPNETCore: java.lang.Exception: connecting to channel "DAPNET1.1.3.1-SNAPSHOT" failed
````

**Comment by Taronyu** [comment]
Müssen wir uns morgen mal ansehen. Ich hatte gerade noch einen Bug in der getName() Methode gefunden, da war der Packagename falsch. Das hat bei meinem lokalen Test aber leider nicht geholfen.

**Comment by Taronyu** [comment]
Das dürfte sich mit der Umstellung auf JGroups SimpleToken zur Authentifizierung auch erst einmal erledigt haben.
