### ISSUE TITLE
Setzen von News geht schief 

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Core#85]
Mit neuer Release 1.1.3.0 und neuem Webinterface
News in Eintrag 1: Geht
Erneuter Eintrag in 1: Geht, wird überschrieben.
Neuer Eintrag in 2: (News an Stelle 2 ist zu diesem Zeitpunk leer)
````
16:23:57.356 [Incoming-1,DAPNET1.1.3.0,db0sda_test] ERROR org.dapnet.core.cluster.RpcListener - Exception :
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_91]
        at java.util.LinkedList.set(LinkedList.java:490) ~[?:1.8.0_91]
        at org.dapnet.core.model.NewsList.add(NewsList.java:73) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.cluster.RpcListener.postNews(RpcListener.java:231) [dapnet-core-1.1.3.0.jar:1.1.3.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.jgroups.blocks.MethodCall.invoke(MethodCall.java:286) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RpcDispatcher.handle(RpcDispatcher.java:321) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RequestCorrelator.handleRequest(RequestCorrelator.java:467) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RequestCorrelator.dispatch(RequestCorrelator.java:406) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RequestCorrelator.receiveMessage(RequestCorrelator.java:357) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.RequestCorrelator.receive(RequestCorrelator.java:245) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:664) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.JChannel.up(JChannel.java:760) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:1034) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.stack.Protocol.up(Protocol.java:426) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.pbcast.FLUSH.up(FLUSH.java:511) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.stack.Protocol.up(Protocol.java:426) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.FRAG2.up(FRAG2.java:182) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.FlowControl.up(FlowControl.java:438) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:294) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:487) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.pbcast.NAKACK2.deliverBatch(NAKACK2.java:989) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.pbcast.NAKACK2.removeAndPassUp(NAKACK2.java:919) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:851) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:611) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:155) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.FD.up(FD.java:260) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:325) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.MERGE3.up(MERGE3.java:292) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.AUTH.up(AUTH.java:150) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.Discovery.up(Discovery.java:296) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.stack.Protocol.up(Protocol.java:380) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.TP.passMessageUp(TP.java:1657) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at org.jgroups.protocols.TP$3.run(TP.java:1591) [jgroups-3.6.11.Final.jar:3.6.11.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
16:23:57.361 [Incoming-1,DAPNET1.1.3.0,db0sda_test] ERROR org.dapnet.core.cluster.RpcListener - PostNews News{rubricName='asda', number=2}: INTERNAL_ERROR
16:23:57.364 [grizzly-http-server-1] ERROR org.dapnet.core.cluster.ClusterManager - Response: [sender=db0sda_testvalue=INTERNAL_ERROR, received=true, suspected=false]

16:23:57.364 [grizzly-http-server-1] FATAL org.dapnet.core.cluster.ClusterManager - Insecure Cluster State
16:23:57.366 [grizzly-http-server-1] ERROR org.dapnet.core.rest.exceptionHandling.ExceptionHandler - POST news/ - Internal Server Error (5000)
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.dapnet.core.rest.resources.AbstractResource.handleObject(AbstractResource.java:158) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at org.dapnet.core.rest.resources.NewsResource.postNews(NewsResource.java:69) ~[dapnet-core-1.1.3.0.jar:1.1.3.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [jersey-server-2.25.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [jersey-common-2.25.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [jersey-common-2.25.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.25.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.25.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [jersey-common-2.25.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [jersey-common-2.25.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [jersey-server-2.25.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [jersey-server-2.25.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [jersey-container-grizzly2-http-2.25.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [grizzly-http-server-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593) [grizzly-framework-2.3.28.jar:2.3.28]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573) [grizzly-framework-2.3.28.jar:2.3.28]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
````

**Comment by dh3wr** [comment]
POST-DATEN:
``{"text":"2. Eintrag","rubricName":"asda","number":2}``

**Comment by Taronyu** [comment]
Die Logik ist wie momentan folgt implementiert:

Wenn Nummer der News gleich 0 ist (also keine Nummer gesetzt), dann setze die News an den Anfang der Liste und verschiebe alle Elemente um 1 nach hinten. Entferne die letzte News falls die Liste mehr als 10 Elemente enthält. Das geht rein über die Position in der Liste, wenn man also manuell eine neuere News auf den 10. Platz setzt, dann fliegt die halt trotzdem raus, obwohl es ältere News gibt.

Wenn eine Nummer größer 0 angegeben wird, dann wird das Minimum aus Nummer und Größe der Liste berechnet (hier gibt es tatsächlich einen Bug...) und dann die News an das gefundene Minimum gesetzt. Wenn die Liste also nur ein Element hat und man gibt Nummer 2 an, dann wird die News im ersten Slot überschrieben (sofern ich den Bug fixe). Es wird also keine News hinten angehangen, wenn der Slot noch keine News enthält.

**Comment by dh3wr** [comment]
Ich habe @MarvinMenzerath gebeten, in der Webinterface eine Option einzubauen, ob an eine Nummer angeben will oder nicht.
@Taronyu Das heißt, der einzige Weg in Nummer 2 etwas explizit hineinzubekommen ist:
1. Merke dir Nummer 1
2. Füge mit Nummer 2 den Inhalt von 2 hinzu
3. Füge den gemerkten Inhalt aus Nummer 1 **ohne Nummer** hinzu.

Es gibt Anwendungen, da will man explizit an eine Nummer einen Eintrag setzen, egal, was sonst so in der Liste ist. Auch wenn es dann "Löcher" geben würde. Kann man das nicht auch einbauen?

**Comment by Taronyu** [comment]
Wenn die Liste nur zwei Elemente enthält, besteht die Liste auch nur aus zwei Elementen. Es gibt dann die Elemente 3-10 noch gar nicht. Deswegen kann da auch nicht per Index zugegriffen werden. Wenn man die Position explizit angeben muss und wir uns von dem "ohne Nummer nach vorne und alle rutschen eins nach hinten" verabschieden, dann geht das. Dann würde ich nämlich einfach ein 10-elementiges Array an der Stelle nehmen und gut ist.

**Comment by dh3wr** [comment]
Joar, das wäre doch was. Und für die Aussendung dann eine Überprüfung: "Wenn Inhalt leer, dann nicht senden". Aber das mit dem automatisch schieben als Option bei keiner Nummernangabe wäre auch cool. Geht nicht beides? Also Array leer initialisieren, Wahlfreier Zugriff zum Schreiben und ein Einfügen ohne Nummer schiebt alle vorherigen Nachrichten eins hoch. Ist eine Nummer leer, so wird deren Inhalt nicht berücksichtig. Also ein "Loch" würde dann von selbst geschlossen werden.

**Comment by Taronyu** [comment]
Sowas hatte ich mir auch gerade überlegt. Bei Arrays ist das halt nur massiv ineefizient und ich halte in der gesamten Zeit ein Mutex auf die Newsliste. Mal gucken, vielleicht geht das trotzdem.
